CREATE TABLE `boss_kill_log` (
`kill_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`guid` INT UNSIGNED NOT NULL ,
`entry` INT UNSIGNED NOT NULL ,
`name` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
`killers` LONGTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;